sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t avattam/docker-multi-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true avattam/docker-multi-react-test npm test -- --coverage



after_success:
  uses: 
    - docker/build-push-action@v2
  - docker build -t avattam/multi-client ./client
  - docker build -t avattam/multi-nginx ./nginx
  - docker build -t avattam/multi-server ./server
  - docker build -t avattam/multi-worker ./worker
  # Log in to the docker CLI
  - docker logout
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push avattam/multi-client
  - docker push avattam/multi-nginx
  - docker push avattam/multi-server
  - docker push avattam/multi-worker
